function(add_kdtest name)
    cmake_parse_arguments(ARG "WILL_FAIL" "" "" ${ARGN})
    add_executable(${name} ${name}.f90)
    target_link_libraries(${name} PRIVATE kdtree)
    add_test(NAME ${name} COMMAND ${name})
    if(ARG_WILL_FAIL)
        set_tests_properties(${name} PROPERTIES WILL_FAIL TRUE)
    endif()
endfunction()

function(add_kdtest_omp name)
    cmake_parse_arguments(ARG "WILL_FAIL" "" "" ${ARGN})
    add_executable(${name} ${name}.f90)
    target_link_libraries(${name} PRIVATE kdtree OpenMP::OpenMP_Fortran)
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES ENVIRONMENT "OMP_NUM_THREADS=4")
    if(ARG_WILL_FAIL)
        set_tests_properties(${name} PROPERTIES WILL_FAIL TRUE)
    endif()
endfunction()
